# Help:
#   MultiLanguge: This will enable MultiLanguge support for all players, Players will see differnet
#                       death messages according to their language set on their settings.
MultiLanguge: true
MainLanguage: "en_us"
